name: Daily cleanup (users & user_skill)

on:
  schedule:
    - cron: "0 21 * * *" # JST 6:00（cronはUTC）
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run cleanup (dry-run)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DRY_RUN: "1"
          TZ: Asia/Tokyo
        run: node --loader ts-node/esm ./batch/index.ts

      - name: Run cleanup batch
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          TZ: Asia/Tokyo
          TS_NODE_PROJECT: tsconfig.batch.json
        run: node --loader ts-node/esm ./batch/index.ts
